import { randomBytes } from 'crypto';
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const ROOT = resolve(__dirname, '..');

function newObjectIdHex(): string {
  return randomBytes(12).toString('hex');
}

// ── Jutsu ranks ──────────────────────────────────────────────────────────────

const JUTSU_RANKS = [
  { name: 'E-Rank', order: 1, dt_cost: 10 },
  { name: 'D-Rank', order: 2, dt_cost: 25 },
  { name: 'C-Rank', order: 3, dt_cost: 50 },
  { name: 'B-Rank', order: 4, dt_cost: 100 },
  { name: 'A-Rank', order: 5, dt_cost: 200 },
  { name: 'S-Rank', order: 6, dt_cost: 500 },
].map((r) => ({ ...r, _id: newObjectIdHex() }));

// ── Element mapping ──────────────────────────────────────────────────────────

const TYPE_TO_ELEMENTS: Record<string, string[]> = {
  'Fire Release': ['katon'],
  'Water Release': ['suiton'],
  'Earth Release': ['doton'],
  'Wind Release': ['futon'],
  'Lightning Release': ['raiton'],
};

// ── Keyword normalization ────────────────────────────────────────────────────

const KEYWORD_FIXES: Record<string, string> = {
  'Bukijutus': 'Bukijutsu',
  'Fuinjutsul': 'Fuinjutsu',
};

function normalizeKeyword(raw: string): string {
  let k = raw.trim().replace(/\s*&[a-z]+;/gi, '').replace(/\.+$/, '').trim();
  return KEYWORD_FIXES[k] ?? k;
}

// ── TSV parsing ──────────────────────────────────────────────────────────────

const lines = readFileSync(resolve(ROOT, 'docs/jutsuList.tsv'), 'utf-8').split('\n');

interface RawRow {
  name: string;
  jutsuType: string;
  rank: string;
  castingTime: string;
  range: string;
  duration: string;
  components: string;
  chakraCost: string;
  keywords: string[];
  description: string;
  atHigherRanks: string | null;
}

const rawRows: RawRow[] = [];
for (let i = 1; i < lines.length; i++) {
  const cols = lines[i].split('\t');
  const name = cols[0]?.trim();
  if (!name) continue;
  rawRows.push({
    name,
    jutsuType: cols[1]?.trim() ?? '',
    rank: cols[2]?.trim() ?? '',
    castingTime: cols[3]?.trim() ?? '1 Action',
    range: cols[4]?.trim() ?? 'Self',
    duration: cols[5]?.trim() ?? 'Instant',
    components: cols[6]?.trim() ?? '',
    chakraCost: cols[7]?.trim() ?? '',
    keywords: [...new Set(
      (cols[8] ?? '').split(',').map(normalizeKeyword).filter(Boolean)
    )],
    description: cols[9]?.trim() ?? '',
    atHigherRanks: cols[10]?.trim() || null,
  });
}

// ── Collect unique keywords and assign IDs ───────────────────────────────────

const keywordIdByName = new Map<string, string>();
for (const row of rawRows) {
  for (const kw of row.keywords) {
    if (!keywordIdByName.has(kw)) {
      keywordIdByName.set(kw, newObjectIdHex());
    }
  }
}

const keywords = [...keywordIdByName.entries()].map(([name, _id]) => ({ _id, name }));

// ── Build jutsu entries ──────────────────────────────────────────────────────

const rankIdByName = new Map(JUTSU_RANKS.map((r) => [r.name, r._id]));

const jutsus = rawRows
  .filter((row) => rankIdByName.has(row.rank))
  .map((row) => ({
    _id: newObjectIdHex(),
    name: row.name,
    jutsu_rank_id: rankIdByName.get(row.rank)!,
    keyword_ids: row.keywords.map((kw) => keywordIdByName.get(kw)!).filter(Boolean),
    elements: TYPE_TO_ELEMENTS[row.jutsuType] ?? [],
    casting_time: row.castingTime,
    range: row.range,
    chakra_cost: row.chakraCost,
    components: row.components,
    duration: row.duration,
    description: row.description,
    at_higher_ranks: row.atHigherRanks,
  }));

const skipped = rawRows.length - jutsus.length;
if (skipped > 0) {
  console.warn(`Skipped ${skipped} row(s) with unrecognised rank.`);
}

// ── Serialise to TypeScript ──────────────────────────────────────────────────

function serialize(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[${value.map(serialize).join(', ')}]`;
  }
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${serialize(v)}`)
      .join(', ');
    return `{ ${entries} }`;
  }
  return JSON.stringify(value);
}

function serializeArray(label: string, type: string, items: unknown[]): string {
  const body = items.map((item) => `  ${serialize(item)},`).join('\n');
  return `export const ${label}: ${type}[] = [\n${body}\n];\n`;
}

const output = [
  `// AUTO-GENERATED by scripts/generate-jutsu-seed.ts — do not edit by hand`,
  `import { IJutsuV1Dto } from '@danrekki/shared/domains/jutsu-v1/core/types';`,
  `import { IJutsuRankV1Dto } from '@danrekki/shared/domains/jutsu-rank-v1/core/types';`,
  `import { IKeywordV1Dto } from '@danrekki/shared/domains/release-v1/core/types';`,
  ``,
  `const NOW = '1970-01-01T00:00:00.000Z';`,
  ``,
  serializeArray('SEED_JUTSU_RANKS', 'IJutsuRankV1Dto',
    JUTSU_RANKS.map((r) => ({ ...r, created_at: 'NOW', updated_at: 'NOW' }))),
  serializeArray('SEED_KEYWORDS', 'IKeywordV1Dto',
    keywords.map((k) => ({ ...k, created_at: 'NOW', updated_at: 'NOW' }))),
  serializeArray('SEED_JUTSUS', 'IJutsuV1Dto',
    jutsus.map((j) => ({ ...j, created_at: 'NOW', updated_at: 'NOW' }))),
].join('\n');

// Replace the string literal "NOW" (with quotes) back to the NOW variable reference
const finalOutput = output.replace(/"NOW"/g, 'NOW');

const outPath = resolve(ROOT, 'apps/api/src/seeds/jutsu-seed-data.ts');
writeFileSync(outPath, finalOutput, 'utf-8');

console.log(`Generated ${jutsus.length} jutsus, ${JUTSU_RANKS.length} ranks, ${keywords.length} keywords → ${outPath}`);
